version: "3.8"

services:
  attendance-api:
    build: .
    container_name: attendance-api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    env_file:
      - .env

# Volumes only needed if you are still persisting local files
volumes:
  uploads:
