version: '3.8'

services:
  attendance-api:
    build: .
    container_name: attendance-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    # --- ADD THIS SECTION ---
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ------------------------
    restart: always
    environment:
      - TZ=Asia/Phnom_Penh